### ISSUE TITLE
[BUG] -  DialogFragment usage of CropImageView leads to crash

### ISSUE THREAD

**Issue by omkar-tenkale** [CanHub/Android-Image-Cropper#116]
**Describe the bug**
Crash on setting image source uri

**To Reproduce**
CropImageView view = mDialog.getView().findViewById(R.id.cropImageView)
cropImageView.setImageUriAsync(Uri.fromFile(myImageFile));

**Expected behavior**
Load the image in cropview

**Actual Behaviour**
Application crash with following stack trace

**Additional context**
 ```
   java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to androidx.fragment.app.FragmentActivity
        at com.canhub.cropper.CropImageView.setImageUriAsync(CropImageView.kt:734)
        at my.app.dialog.CropImageDialog.onInitDialog(CropImageDialog.java:53)
        at my.app.dialog.BottomDialog.onCreateDialog(BottomDialog.java:39)
        at androidx.fragment.app.DialogFragment.prepareDialog(DialogFragment.java:645)
        at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:559)
        at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1652)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:490)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2177)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2088)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1990)
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by Canato** [comment]
Hello @omkar-tenkale Welcome!

Could you please provide some more information?
- Library version
- Which OS are you testing it
- The code you used to call the library
- The code you add in your manifest to use the library
- What `Theme` your app use for layout.

On **Steps to reproduce** I cannot use this steps to reproduce =/
`findViewbyId` which id are you using? which view? is a library view?
`setImageUri()` are you using this without parameter? we have 3 functions in this library that has this signature depending on how are you using. which one of them? 

Thanks =D

**Comment by omkar-tenkale** [comment]
Issue title with a clear name for the bug
    Library version: 3.0.0
    Which OS are you testing it : Android 11 LineageOS
    The code you used to call the library: 

```
CropImageView view = mDialog.getView().findViewById(R.id.cropImageView)
cropImageView.setImageUriAsync(Uri.fromFile(myImageFile));
```
    
The code you add in your manifest to use the library
> Manifest? Nothing

 
What Theme your app use for layout.
>     <style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar">


I think the root cause of issue is using the view in **DialogFragment**
`androidx.fragment.app.DialogFragment`

**Comment by omkar-tenkale** [comment]
https://github.com/Nescafemix/hintcase/issues/20#issuecomment-258070176

**Comment by Canato** [comment]
Hey @omkar-tenkale thank for exemplify more!

Indeed this is a context issue.
Not sure if the library can support the usage of DialogFragment.

My suggestion would be to add a DialogFragment sample in our code base, in the sample module.
So I can reproduce and you or another person can make the tweeks to make it work
