### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by demed97** [CanHub/Android-Image-Cropper#12]
Hi. I have java.lang.NullPointerException: Attempt to invoke virtual method 'void com.theartofdev.edmodo.cropper.CropImageView.setOnSetImageUriCompleteListener(com.theartofdev.edmodo.cropper.CropImageView$OnSetImageUriCompleteListener)' on a null object reference when i try start activity whith this code from fragment 
CropImage.activity()
                .setGuidelines(CropImageView.Guidelines.ON)
                .start(requireContext(), this)
![image](https://user-images.githubusercontent.com/64464695/101907310-0b595f00-3bc3-11eb-934b-389a3b7d8fe3.png)

**Comment by Canato** [comment]
I can see that you are using `com.theartofdev.edmodo.cropper` you need to migrate 

[here you have a guide for it.](https://github.com/CanHub/Android-Image-Cropper/wiki/%F0%9F%9A%A8-How-to-migrate-Android-Image-Cropper--%F0%9F%9A%A8)

**Comment by demed97** [comment]
hi @Canato. after migration i have the same problems
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.tallium.eubank.smartbank, PID: 9601
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.canhub.cropper.CropImageView.setOnSetImageUriCompleteListener(com.canhub.cropper.CropImageView$OnSetImageUriCompleteListener)' on a null object reference
        at com.canhub.cropper.CropImageActivity.onStart(CropImageActivity.java:101)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1433)
        at android.app.Activity.performStart(Activity.java:7980)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3578)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2220)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8016)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1087)

**Comment by Canato** [comment]
I'm not sure @demed97 because `CropImageActivity.java:101` has exactly a null checker.
Maybe this will be solved when we update the project to kotlin

**Comment by Canato** [comment]
I just open a PR with `CropImageActivity` into kotlin. #16 

Hopefully will fix this annoying bug

**Comment by demed97** [comment]
I found the problem. It is related to the fact that the name crop_image_activity conflicted with another library com.regula.documentreader.api.CropImageActivity and com.theartofdev.edmodo.cropper.CropImageActivity. If possible, you can change the name crop_image_activity to something more original in the future
