### ISSUE TITLE
[BUG] - AppCompat widget that can only be used with a Theme.AppCompat theme

### ISSUE THREAD

**Issue by Akshay0701** [CanHub/Android-Image-Cropper#150]
- Lib Version [e.g. 1.1.0]
 
**Describe the bug**
application crashed with a message in logcat 
```
2021-06-26 12:51:45.595 30624-30624/com.ichi2.anki E/ThemeUtils: View class androidx.appcompat.widget.AppCompatImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
2021-06-26 12:51:45.615 30624-30624/com.ichi2.anki E/com.ichi2.anki: Invalid ID 0x00000000.
2021-06-26 12:51:45.618 30624-30624/com.ichi2.anki E/com.ichi2.anki: Invalid ID 0x00000000.
2021-06-26 12:51:45.625 30624-30624/com.ichi2.anki E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ichi2.anki, PID: 30624
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki/com.canhub.cropper.CropImageActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3611)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3775)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2246)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:8010)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
     Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:846)
        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:809)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:687)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:201)
        at com.canhub.cropper.CropImageActivity.onCreate(CropImageActivity.kt:56)
        at android.app.Activity.performCreate(Activity.java:8006)
        at android.app.Activity.performCreate(Activity.java:7990)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3584)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3775) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2246) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:233) 
        at android.app.ActivityThread.main(ActivityThread.java:8010) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978) 

```

**To Reproduce**
wrttien this code in my activity 
 ``` java
CropImage.activity(mPreviousImageUri)
                    .setActivityTitle("sample")
                    .start(mActivity);
```

**Comment by Akshay0701** [comment]
I completely understand this error is not caused by your library, 
and please suggest to me what should I change in the above code to get rid of this error/crash

**Comment by connyduck** [comment]
> You need to use a Theme.AppCompat theme (or descendant) with this activity.

Define it in your manifest like this:
```xml
<activity
      android:name="com.canhub.cropper.CropImageActivity"
      android:theme="@style/Base.Theme.AppCompat" />
```

**Comment by Akshay0701** [comment]
Thank You so much @connyduck, 
and I am really thankful to @Canato for this wonderful library.
