### ISSUE TITLE
[BUG] - Image Too Large

### ISSUE THREAD

**Issue by dkmalviya** [CanHub/Android-Image-Cropper#221]
Application getting crashed if we capturing/uploading image above 5 MB.

Fatal Exception: java.lang.RuntimeException: Canvas: trying to draw too large(253247232bytes) bitmap.
       at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:281)
       at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:91)
       at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:548)
       at android.widget.ImageView.onDraw(ImageView.java:1453)
       at android.view.View.draw(View.java:23901)
       at android.view.View.updateDisplayListIfDirty(View.java:22776)
       at android.view.View.draw(View.java:23631)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
       at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1994)
       at android.view.View.draw(View.java:23904)
       at android.view.View.updateDisplayListIfDirty(View.java:22776)
       at android.view.View.draw(View.java:23631)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
       at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1994)
       at android.view.View.updateDisplayListIfDirty(View.java:22762)
       at android.view.View.draw(View.java:23631)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
       at android.view.View.draw(View.java:23904)
       at androidx.core.widget.NestedScrollView.draw(NestedScrollView.java:1999)
       at android.view.View.updateDisplayListIfDirty(View.java:22776)
       at android.view.View.draw(View.java:23631)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
       at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1994)
       at android.view.View.updateDisplayListIfDirty(View.java:22762)
       at android.view.View.draw(View.java:23631)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
       at android.view.View.updateDisplayListIfDirty(View.java:22762)
       at android.view.View.draw(View.java:23631)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
       at android.view.View.draw(View.java:23904)
       at android.view.View.updateDisplayListIfDirty(View.java:22776)
       at android.view.View.draw(View.java:23631)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
       at android.view.View.updateDisplayListIfDirty(View.java:22762)
       at android.view.View.draw(View.java:23631)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
       at android.view.View.updateDisplayListIfDirty(View.java:22762)
       at android.view.View.draw(View.java:23631)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
       at android.view.View.updateDisplayListIfDirty(View.java:22762)
       at android.view.View.draw(View.java:23631)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
       at android.view.View.updateDisplayListIfDirty(View.java:22762)
       at android.view.View.draw(View.java:23631)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
       at android.view.View.updateDisplayListIfDirty(View.java:22762)
       at android.view.View.draw(View.java:23631)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
       at android.view.View.updateDisplayListIfDirty(View.java:22762)
       at android.view.View.draw(View.java:23631)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
       at android.view.View.draw(View.java:23904)
       at com.android.internal.policy.DecorView.draw(DecorView.java:1282)
       at android.view.View.updateDisplayListIfDirty(View.java:22776)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:579)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:585)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:662)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:5042)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4749)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3866)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2618)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9965)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1010)
       at android.view.Choreographer.doCallbacks(Choreographer.java:809)
       at android.view.Choreographer.doFrame(Choreographer.java:744)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8506)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)

Steps to reproduce:
1. Capture image with full resolution
2. scale it to full 
3. click on crop button 

After click on crop , app is getting crashed.

 - Device: [Samsung all devices]
 - OS: [11]

**Comment by Canato** [comment]
Not sure the best approach here, will try to think about something 🤔

**Comment by Ekalips** [comment]
@dkmalviya Issue might be with your image itself. When you are looking at your "5mb" image, you are actually looking at "compressed" image (jpeg, png, etc). Where's android's bitmap is measured as a raw image. To check your raw image size you should do `width * height * quality` (quality is ARGB_8888 by default = 4). From the exception above your image weights like 253mb raw (width*height*4). If you are loading your image from the local asset (drawable) - try moving your image into a different folder (eg drawable-xxhdpi or greater), it'll enable android native image resizing. If you are loading an image from the network - resize it on a flight. There's no point in bitmap that is larger than your typical screen (eg FullHD is 1920×1080, so even if it's a full-screen image, FullHD image will take only ~8mb)

If you really need to resize like 8k+ image, I doubt that this lib would help you. Resizing such image would require tiling and complex calculations. Or lib itself should resize drawn image and then crop original bitmap respectively. But having such bitmap in memory would kill most low to mid-end devices 🤔

**Comment by alexanderbkl** [comment]
When loading image to ImageView, try using Glide or Picasso or something like that, thon put a raw image URI to IV (don't do imageView.setURI(uri)).

**Comment by shivanigupta22** [comment]
Any updates on this?

**Comment by pratyaksh1610** [comment]
I would like to work on this issue . pls assign this issue to me. @Canato @dkmalviya

**Comment by pratyaksh1610** [comment]
So can u assign some other good first issue, I really wanted to contribute to real world projects.

**Comment by pratyaksh1610** [comment]
@Canato

**Comment by Canato** [comment]
Hey @pratyaksh1610 Happy that you are excited to help our project. For sure will be amazing having your contribution.

You tagged me and tagged me again 1 hour later, sorry that I could not reply as fast as you expected, but I have a normal day-to-day job and this is volunteer work. So sometimes takes me hours even days to have a space to come here.

That said we have this list of possible features https://github.com/CanHub/Android-Image-Cropper/contribute
You can choose the one that fits you better ^^

**Comment by Canato** [comment]
@Ekalips do you believe we should close this? I will remove the `pinned` label and if no one oppose the stale bot will close this.
