### ISSUE TITLE
[BUG] - Resolved path jumped beyond configured root

### ISSUE THREAD

**Issue by dkmalviya** [CanHub/Android-Image-Cropper#239]
- Lib Version 3.3.5
 
Fatal Exception: java.lang.SecurityException: Resolved path jumped beyond configured root
       at androidx.core.content.FileProvider$SimplePathStrategy.getFileForUri(FileProvider.java:839)
       at androidx.core.content.FileProvider.openFile(FileProvider.java:620)
       at android.content.ContentProvider.openAssetFile(ContentProvider.java:2027)
       at android.content.ContentProvider.openAssetFile(ContentProvider.java:2091)
       at android.content.ContentProvider$Transport.openAssetFile(ContentProvider.java:498)
       at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1843)
       at android.content.ContentResolver.openOutputStream(ContentResolver.java:1545)
       at com.canhub.cropper.BitmapUtils.writeBitmapToUri(BitmapUtils.java:433)
       at com.canhub.cropper.BitmapCroppingWorkerJob$start$1$1.invokeSuspend(BitmapCroppingWorkerJob.java:85)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:106)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:571)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.java:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.java:678)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java:665)

app is crashed after click on crop button.

 - Device:Redmi K20
 - Android 11

**Comment by Canato** [comment]
@dkmalviya cannot reproduce, could you provide a video showing it on the Sample app? Thanks
