### ISSUE TITLE
[BUG] -  java.lang.IllegalArgumentException: column '_data' does not exist. Available columns: [] in Android 11

### ISSUE THREAD

**Issue by jerinamathews** [CanHub/Android-Image-Cropper#263]
🚨🚨 Before open the ticket please check if you can reproduce the bug in the sample code

 - Lib Version [e.g. 3.3.6]
 
**Describe the bug**
I want to process the cropped image generated, and I have the following code to convert the uri to file,
     String img = ContentUriUtils.INSTANCE.getFilePath(context, uri);
     File f = new File(img);

> 021-11-13 23:15:01.105 25443-27751/com. W/System.err: java.lang.IllegalArgumentException: column '_data' does not exist. Available columns: []
2021-11-13 23:15:01.105 25443-27751/com. W/System.err:     at android.database.AbstractCursor.getColumnIndexOrThrow(AbstractCursor.java:351)
2021-11-13 23:15:01.105 25443-27751/com. W/System.err:     at android.database.CursorWrapper.getColumnIndexOrThrow(CursorWrapper.java:91)
2021-11-13 23:15:01.105 25443-27751/com. W/System.err:     at droidninja.filepicker.utils.ContentUriUtils.getFilePath(ContentUriUtils.kt:61)
2021-11-13 23:15:01.105 25443-27751/com. W/System.err:     at com..Activities.MainActivity$ConvertImages.doInBackground(MainActivity.java:970)
2021-11-13 23:15:01.105 25443-27751/com. W/System.err:     at com..Activities.MainActivity$ConvertImages.doInBackground(MainActivity.java:875)
2021-11-13 23:15:01.105 25443-27751/com. W/System.err:     at android.os.AsyncTask$3.call(AsyncTask.java:394)
2021-11-13 23:15:01.105 25443-27751/com. W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2021-11-13 23:15:01.105 25443-27751/com. W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
2021-11-13 23:15:01.105 25443-27751/com. W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2021-11-13 23:15:01.105 25443-27751/com. W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2021-11-13 23:15:01.105 25443-27751/com. W/System.err:     at java.lang.Thread.run(Thread.java:923)

its returning following error

**To Reproduce**

**Expected behavior**

**Media**
Please add screenshots and/or screen recordings to help explain your problem.
We cannot help without more information

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 3XL]

**Additional context**

**Comment by Canato** [comment]
@jerinamathews the library has methods to get the file.

On the README we show
```kt
 val uriContent = result.uriContent 
val uriFilePath = result.getUriFilePath(context) // optional usage
```

In the sample code we show other ways of doing this, java included.

Please use our method for it and if does not work let me know so we can reopen the issue
