### ISSUE TITLE
[BUG] - Fatal Exception: android.content.res.Resources$NotFoundException: Resource ID #0x7f080126

### ISSUE THREAD

**Issue by hiteshsarsava** [CanHub/Android-Image-Cropper#269]
- Lib Version [3.3.5]
 
**Describe the bug**
App is got crash in only NEXUS 5X device. I am attaching here the log of crash which is received in crashlytics

**CrashLog**
```kt
Fatal Exception: android.content.res.Resources$NotFoundException: Resource ID #0x7f080126
       at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:215)
       at android.content.res.Resources.getValue(Resources.java:1316)
       at androidx.appcompat.widget.ResourceManagerInternal.createDrawableIfNeeded(ResourceManagerInternal.java:179)
       at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:144)
       at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:135)
       at androidx.appcompat.content.res.AppCompatResources.getDrawable(AppCompatResources.java:104)
       at androidx.appcompat.view.menu.MenuItemImpl.getIcon(MenuItemImpl.java:505)
       at androidx.appcompat.view.menu.ActionMenuItemView.initialize(ActionMenuItemView.java:126)
       at androidx.appcompat.widget.ActionMenuPresenter.bindItemView(ActionMenuPresenter.java:207)
       at androidx.appcompat.view.menu.BaseMenuPresenter.getItemView(BaseMenuPresenter.java:188)
       at androidx.appcompat.widget.ActionMenuPresenter.getItemView(ActionMenuPresenter.java:193)
       at androidx.appcompat.widget.ActionMenuPresenter.flagActionItems(ActionMenuPresenter.java:495)
       at androidx.appcompat.view.menu.MenuBuilder.flagActionItems(MenuBuilder.java:1176)
       at androidx.appcompat.view.menu.BaseMenuPresenter.updateMenuView(BaseMenuPresenter.java:96)
       at androidx.appcompat.widget.ActionMenuPresenter.updateMenuView(ActionMenuPresenter.java:226)
       at androidx.appcompat.view.menu.MenuBuilder.dispatchPresenterUpdate(MenuBuilder.java:292)
       at androidx.appcompat.view.menu.MenuBuilder.onItemsChanged(MenuBuilder.java:1063)
       at androidx.appcompat.view.menu.MenuBuilder.startDispatchingItemsChanged(MenuBuilder.java:1090)
       at androidx.appcompat.app.AppCompatDelegateImpl.preparePanel(AppCompatDelegateImpl.java:1949)
       at androidx.appcompat.app.AppCompatDelegateImpl.doInvalidatePanelMenu(AppCompatDelegateImpl.java:2188)
       at androidx.appcompat.app.AppCompatDelegateImpl$2.run(AppCompatDelegateImpl.java:271)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```
I thought the issue is within my app core drawables used. But when I used [this](https://stackoverflow.com/questions/60677193/how-to-find-resource-id-s-now-that-android-studio-no-longer-creates-r-java)  to find out which drawable is doing the crash. I found below attached screenshot.

![image](https://user-images.githubusercontent.com/16486943/142359868-480f0fa4-fda4-4a37-9ac1-d22e13fcea18.png)

Then after check in project. Which lib is using this resource file. I found below attached screenshot

![image](https://user-images.githubusercontent.com/16486943/142360336-4b7a8f73-1a4f-42d3-add9-2c7246506dd8.png)

**To Reproduce**
Use in below mentioned device.

**Expected behavior**
It should not crash in any device because of resource file. File should place in anydpi resource folder to prevent this.

**Media**
Please add screenshots and/or screen recordings to help explain your problem.
Added all required screenshots in description.

**Smartphone (please complete the following information):**
![image](https://user-images.githubusercontent.com/16486943/142360748-4124f25a-62fb-4183-9229-75b67c31ea8c.png)

**Comment by Canato** [comment]
Hey @hiteshsarsava thanks for the detailed issue, helps a lot to get context

> File should place in anydpi resource folder to prevent this.

The icon is a vector, do we have any issues in this device related to vectors? is strange that it say `NotFoundException` because the xml vector is there 🤔

**Comment by hiteshsarsava** [comment]
@Canato I am also using other vector icons. But it is not creating any problem or crash.

**Comment by Canato** [comment]
Not sure what we can do here @hiteshsarsava open to suggestions

**Comment by hiteshsarsava** [comment]
@Canato I think you can place this vector in anydpi folder to accept this configuration for any device to accept it.

**Comment by Canato** [comment]
@hiteshsarsava please open a PR with the vector in the place it work for you and we can merge it ^^

**Comment by hiteshsarsava** [comment]
Ok. @Canato Will take time and update you with PR. Thanks.

**Comment by sanvean** [comment]
Hi @hiteshsarsava @Canato was a PR ever raised and merged for this issue? As seeing the same crash with library version 4.1.0 (same device type - Nexus 5X running Android 8.1.0).

**Comment by Canato** [comment]
@sanvean no PR was open for it (nothing linked on this issue) and the stale bot close it cause no one was working on it =/

**Comment by sanvean** [comment]
Ah I see. @hiteshsarsava any chance you could submit the PR for this one? Sounds like you've identified the exact change required to solve this issue?

**Comment by abinhho** [comment]
Issue still there.

**Comment by Canato** [comment]
@abinhho Can you please open a PR with a solution for it?

**Comment by abinhho** [comment]
@Canato I hope I can, I will if I found the right reason. I am researching about the reason. 
Because my users said:
- When resize image -> crashed (Unknown device) - maybe user used two fingers to resize and crashed at this time.
- When clicked crop button -> crashed (Galaxy Note 20 Ultra)

I check Crashlytics and also saw `ResourceNotFoundException` but not sure is it true. Because crop screen is shown, so resource not found should not happen.

Also, icons resource already on `drawable` folder. Put it in this folder is enough I think. So why do we need `anydpi`? (still researching...).
