### ISSUE TITLE
[BUG] - "4.0.0"->App crash when clicking on "SAMPLE CALLING CROP IMAGE JAVA->TAKE CAMERA PICTURE BEFORE CALLING LIBRARY WITH URI"

### ISSUE THREAD

**Issue by r4jjin** [CanHub/Android-Image-Cropper#301]
- Lib Version 4.0.0
 
**Describe the bug & Steps to reproduce**
1. Cloned the project and ran the app.
2. [BUG] - App crash when clicking on "SAMPLE CALLING CROP IMAGE JAVA->TAKE CAMERA PICTURE BEFORE CALLING LIBRARY WITH URI"

```
Crash Report
2022-01-12 01:07:54.772 22673-22673/com.example.croppersample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.croppersample, PID: 22673
    java.lang.IllegalArgumentException: Couldn't find meta-data for provider with authority com.example.croppersample.fileprovider
        at androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:662)
        at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:635)
        at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:441)
        at com.canhub.cropper.sample.crop_image_java.app.SCropImageFragmentJava.startTakePicture(SCropImageFragmentJava.java:196)
        at com.canhub.cropper.sample.crop_image_java.app.SCropImageFragmentJava.lambda$onViewCreated$0$SCropImageFragmentJava(SCropImageFragmentJava.java:78)
        at com.canhub.cropper.sample.crop_image_java.app.SCropImageFragmentJava$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:8160)
        at android.widget.TextView.performClick(TextView.java:16222)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1119)
        at android.view.View.performClickInternal(View.java:8137)
        at android.view.View.access$3700(View.java:888)
        at android.view.View$PerformClick.run(View.java:30236)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8633)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Expected behavior**
Image should be captured and should be subjected to cropping.

**Media**
![image](https://user-images.githubusercontent.com/6790174/149010318-00b52855-2b66-4380-8506-01fca60a36c8.png)

**Smartphone (please complete the following information):**
 - Device: Samsung s10 plus
 - OS: Android 11

**Additional context**
I cannot use Java 11 for my project, since it is a commercial application, will it work with Java 8 as well ?

**Comment by Canato** [comment]
This is fixed in the latest code, will not have a release for it

Thanks for raising!
