### ISSUE TITLE
Permission Denial ComponentInfo{com.fakechat.maker.creator.waa/com.canhub.cropper.CropImageActivity}: 

### ISSUE THREAD

**Issue by naveedninesol** [CanHub/Android-Image-Cropper#526]
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.fakechat.maker.creator.waa/com.canhub.cropper.CropImageActivity}: java.lang.SecurityException: Permission Denial: starting Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 cmp=com.sec.android.app.camera/.Camera clip={text/uri-list U:content://com.fakechat.maker.creator.waa.cropper.fileprovider/cached_files/tmp_image_file5200886158179077765.png} (has extras) } from ProcessRecord{dea1d24 11306:com.fakechat.maker.creator.waa/u0a920} (pid=11306, uid=10920) with revoked permission android.permission.CAMERA
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3556)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3703)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2216)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7948)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)

**Comment by vanniktech** [comment]
Yeah you're trying to the use the camera when your user hasn't given you the necessary permission

**Comment by naveedninesol** [comment]
> 

I have given all permission (camera ,  storage) and this crash is coming only on android 11
