### ISSUE TITLE
File not found exception.

### ISSUE THREAD

**Issue by tinhngo-asnet** [CanHub/Android-Image-Cropper#561]
Hi!
I'm facing this crash on Brand:Huawei Model:荣耀 V9 Play run on Android OS: 8.1. May you help to take a look and give me your feedback? Thanks!

`Fatal Exception: java.io.FileNotFoundException: No such file or directory
       at android.os.Parcel.openFileDescriptor(Parcel.java)
       at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:283)
       at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:200)
       at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1004)
       at android.content.ContentResolver.openOutputStream(ContentResolver.java:769)
       at com.canhub.cropper.BitmapUtils.writeBitmapToUri(BitmapUtils.kt:460)
       at com.canhub.cropper.BitmapCroppingWorkerJob$start$1$1.invokeSuspend(BitmapCroppingWorkerJob.kt:96)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)`

**Comment by vanniktech** [comment]
No idea what you're doing. The sample works, please refer to that one.
