### ISSUE TITLE
[BUG] - TransactionTooLargeException

### ISSUE THREAD

**Issue by AmriZakariya** [CanHub/Android-Image-Cropper#67]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.zak.setscanner, PID: 29662
    java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 37498368 bytes
        at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:161)
        at android.os.Handler.handleCallback(Handler.java:888)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8178)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
     Caused by: android.os.TransactionTooLargeException: data parcel size 37498368 bytes
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(BinderProxy.java:526)
        at android.app.IActivityTaskManager$Stub$Proxy.activityStopped(IActivityTaskManager.java:4561)
        at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:145)
        at android.os.Handler.handleCallback(Handler.java:888) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:213) 
        at android.app.ActivityThread.main(ActivityThread.java:8178) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

**Comment by Canato** [comment]
Hey @AmriZakariya thanks for the issue!

To help you we will need some more information! 
- Which library version are you using it?
- How is the step by step to reproduce this bug? (if possible how to reproduce on the library sample)
> Steps to reproduce
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
- Screnshot/video from the bug
- Device used (label and android OS)

**Comment by chriscoomber** [comment]
FWIW I've seen this log with apps that don't include this library.
